name: Release Service

on:
  push:
    tags: "2.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ github.run_number }}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service
      run: dotnet publish --no-build ./src/Service.Backoffice.Blazor/Service.Backoffice.Blazor.csproj --configuration Release --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api

    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
#        registry: docker.pkg.github.com
        registry: ghcr.io
        repository: ${{ secrets.ORG_NAME }}/service.backoffice/service.backoffice
        tags: latest
        build_args: app_version=service.backoffice:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}


    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
#        registry: docker.pkg.github.com
        registry: ghcr.io
        repository: ${{ secrets.ORG_NAME }}/service.backoffice/service.backoffice
        tag_with_ref: true
        build_args: app_version=service.backoffice:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  update_version:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: get uat kube yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetEducation/kubernetes-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=service.backoffice:.*$
        imagename=service.backoffice*:${GITHUB_REF#refs/tags/}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "deployment.*" -print0 -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Update version of service myjetwallet.service.backoffice"
        git push